### ISSUE TITLE
Revitalize Official Telegram Groups

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/ubiquity-os-kernel-telegram#42]
Our official Telegram groups lack engagement, with minimal interaction that often feels transactional and monotonous. There’s a general absence of activity across most channels. This proposal outlines methods to breathe life into these groups and create a sense of vibrancy and competitiveness. 

By implementing these features, we aim to stimulate activity, improve engagement, and create a dynamic environment that benefits contributors, the team, and external stakeholders.

### 1. Monthly Aggregate of Dollars Earned per Contributor (Task Rewards)
- **Purpose:**  
  - Provides quick insight into top performers.  
  - Appealing to new contributors, investors, and the broader community.  
- **Implementation:**  
  - Aggregate and post monthly earnings of contributors.  
  - Share in a dedicated `channel` or `forum` focused on these updates.

### 2. Monthly Aggregate of Tasks Completed per Repository
- **Purpose:**  
  - Summarizes deliverables completed per repo for the month.  
  - Helps track progress and identify remaining work compared to goals (e.g., monthly check-ins/standups).  
  - Useful for investors and core team/management.  
- **Implementation:**  
  - Post a summary in a dedicated `channel` or `forum`.

### 3. Task Completion Shoutouts with Reward Amounts
- **Purpose:**  
  - Highlights daily activity across the organization.  
  - Encourages discussion among contributors, not limited to task watchers.  
  - Appeals to new contributors, investors, community, and the team.  
- **Implementation:**  
  - Announce completed tasks and associated rewards in a dedicated `channel` or `forum`.

---

### Benefits
1. **Regular Updates:**  
   - Keeps the community informed and engaged with meaningful insights.  
2. **Promotes Discussion:**  
   - Opens conversations among contributors and the team.  
3. **Fosters Competitiveness:**  
   - Encourages less active contributors to engage by showcasing the earnings and activity of others.  
   - Example: I've earned $3,800 in the last 30 days from tasks alone, recognition of that would be sweet and would entice less proactive contributors to get more involved.

### Additional Considerations
1. **Unified Notifications:**  
   - Use a single chat for these updates to simplify managing notifications.  
2. **Potential for Partner Expansion:**  
   - Currently, only our orgs can use this feature, but it could be valuable for partners.  
   - Example: Presenting usage of `Ubiquity OS` in a monthly dashboard format, which could eventually evolve into a standalone UI for partners.  

rfc @0x4007 

@zugdev - tagging you as you told me in DMs you ran a hackathon and did devrel etc, what do you think?

If you consider potential partners and their platforms like discord etc they usually have a lot of rooms some dedicated to automated updates like PRs, tweets etc, then others for memes and just random sort of chat not relevant to the broader goals but to allow the community to interact and fester in a `non-work` environment which the official chats all share that kind of vibe.

**Comment by 0x4007** [comment]
> Our official Telegram groups lack engagement, with minimal interaction that often feels transactional and monotonous. There’s a general absence of activity across most channels. This proposal outlines methods to breathe life into these groups and create a sense of vibrancy and competitiveness.

I prefer to have general activity on t.me/UbiquityDevPool instead of t.me/UbiquityDAO. There's a lot of value in maximizing signal-to-noise for urgent work related communications. t.me/UbiquityDAO is one of the very few chats I have pinned for this reason.

Most of the engineering for the monthly aggregates should be on leaderboard.ubq.fi. The numbers should be compiled there and then served via an API for reposting on Telegram. 

Completed tasks could be nice but if its too frequent it will come across as spammy, so maybe once a month or at most, once a week I could see this potentially being interesting. At the same time though, I think it would be nice to have the ability to opt-out of it. Dedicated topics for each announcement type in t.me/UbiquityDevPool (which can be selectively muted) might be the best solution.

**Comment by Keyrxng** [comment]
Implementation is rather simple if implemented within this plugin and less dev time involved:

- on `issue_comment.created && comment === payoutComment`
- capture task assignee and reward amount (already implemented in #13)
- Post Task Completion Shoutout
- store in a JSON on GitHub and accumulate for the month
- cron workflow that runs every month and makes the aggregate posts then clears the JSON


> I prefer to have general activity on t.me/UbiquityDevPool instead of t.me/UbiquityDAO. There's a lot of value in maximizing signal-to-noise for urgent work related communications. t.me/UbiquityDAO is one of the very few chats I have pinned for this reason.

I understand that, my intention is to try and foster a more lively atmosphere which the broader community has something to discuss as it's usually work-related and code specific so it excludes near everyone from being able to join in

> Most of the engineering for the monthly aggregates should be on leaderboard.ubq.fi. The numbers should be compiled there and then served via an API for reposting on Telegram.

This might look like `leaderboard.ubq.fi`:
- having workflows that capture in-real time like above, UI reads from repo JSON vs DB deps which I know we avoid
- scheduled cron which captures and updates everything within a given timeframe
- API logic to serve the JSON? could just fetch it via github directly like we do in `work.ubq` and `devpool-issues`

> Completed tasks could be nice but if its too frequent it will come across as spammy, so maybe once a month or at most, once a week I could see this potentially being interesting. At the same time though, I think it would be nice to have the ability to opt-out of it. Dedicated topics for each announcement type in t.me/UbiquityDevPool (which can be selectively muted) might be the best solution.

Opt-out is easily configurable and I can implement config options for how often any particular thing is posted i.e quarterly, daily, bi-weekly whatever.

**Comment by rndquu** [comment]
The proposed features are basically for the [analytics dashboard](https://github.com/ubiquity-os/dao-analytics). Although the proposed features are nice to have I don't think they should be top priority now.

@Keyrxng You could:
1. Create a new issue in https://github.com/ubiquity-os/dao-analytics describing what steps we need to make https://github.com/ubiquity-os/dao-analytics UI work fine for the ubiquity related organizations
2. Move current github issue to the https://github.com/ubiquity-os/dao-analytics so that we could break it down further into smaller features:
  a) Monthly task rewards UI page
  b) Monthly tasks completed UI page

I don't think current feature should be part of the telegram kernel since in the end it should be possible for the https://github.com/ubiquity-os/dao-analytics to send webhooks to any service capable of receiving them (github, telegram, twitter, etc...)

**Comment by Keyrxng** [comment]
> I don't think current feature should be part of the telegram kernel since in the end it should be possible for the https://github.com/ubiquity-os/dao-analytics to send webhooks to any service capable of receiving them (github, telegram, twitter, etc...)

So with the `real-time collection` task completed we'd be able to run a cron job through either repo that would pull the collected data from the past x days and we could either:

- have `dashboard` ping `kernel-telegram` endpoint and it posts what is sent
- have `kernel-telegram` ping `dashboard` and it posts what is gets a reply to
- cron in `kernel-telegram` simply fetches from the monthly JSON and formats it all pretty and posts

**Comment by rndquu** [comment]
> have `dashboard` ping `kernel-telegram` endpoint and it posts what is sent

+1

**Comment by rndquu** [comment]
Closing in favor of https://github.com/ubiquity-os/dao-analytics/issues/3
